package jdk.prim.util.stream;

import jdk.prim.util.PrimitiveSpliterator;
import jdk.prim.util.function.PrimitiveFunction;

import java.util.Spliterator;

/**
 * @see java.util.stream.PipelineHelper
 */
final class PrimitivePipelineHelper {
    abstract static class OfDouble {
        abstract int getStreamAndOpFlags();
        abstract long exactOutputSizeIfKnownDouble(PrimitiveSpliterator.OfDouble spliterator);
        abstract PrimitiveSink.OfDouble wrapAndCopyIntoDouble(PrimitiveSink.OfDouble sink, PrimitiveSpliterator.OfDouble spl);
        abstract void copyIntoDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract boolean copyIntoWithCancelDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveSink.OfDouble wrapSinkDouble(PrimitiveSink.OfDouble sink);
        abstract PrimitiveSpliterator.OfDouble wrapSpliteratorDouble(PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveNode.OfDouble evaluateDouble(PrimitiveSpliterator.OfDouble spl, boolean flatten, PrimitiveFunction.OfInt<double[]> gen);
        abstract long exactOutputSizeIfKnownLong(PrimitiveSpliterator.OfLong spliterator);
        abstract PrimitiveSink.OfDouble wrapAndCopyIntoLong(PrimitiveSink.OfLong sink, PrimitiveSpliterator.OfLong spl);
        abstract void copyIntoLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract boolean copyIntoWithCancelLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveSink.OfLong wrapSinkLong(PrimitiveSink.OfDouble sink);
        abstract PrimitiveSpliterator.OfDouble wrapSpliteratorLong(PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveNode.OfDouble evaluateLong(PrimitiveSpliterator.OfLong spl, boolean flatten, PrimitiveFunction.OfInt<double[]> gen);
        abstract long exactOutputSizeIfKnownInt(PrimitiveSpliterator.OfInt spliterator);
        abstract PrimitiveSink.OfDouble wrapAndCopyIntoInt(PrimitiveSink.OfInt sink, PrimitiveSpliterator.OfInt spl);
        abstract void copyIntoInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract boolean copyIntoWithCancelInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveSink.OfInt wrapSinkInt(PrimitiveSink.OfDouble sink);
        abstract PrimitiveSpliterator.OfDouble wrapSpliteratorInt(PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveNode.OfDouble evaluateInt(PrimitiveSpliterator.OfInt spl, boolean flatten, PrimitiveFunction.OfInt<double[]> gen);
        abstract long exactOutputSizeIfKnownFloat(PrimitiveSpliterator.OfFloat spliterator);
        abstract PrimitiveSink.OfDouble wrapAndCopyIntoFloat(PrimitiveSink.OfFloat sink, PrimitiveSpliterator.OfFloat spl);
        abstract void copyIntoFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract boolean copyIntoWithCancelFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveSink.OfFloat wrapSinkFloat(PrimitiveSink.OfDouble sink);
        abstract PrimitiveSpliterator.OfDouble wrapSpliteratorFloat(PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveNode.OfDouble evaluateFloat(PrimitiveSpliterator.OfFloat spl, boolean flatten, PrimitiveFunction.OfInt<double[]> gen);
        abstract long exactOutputSizeIfKnownChar(PrimitiveSpliterator.OfChar spliterator);
        abstract PrimitiveSink.OfDouble wrapAndCopyIntoChar(PrimitiveSink.OfChar sink, PrimitiveSpliterator.OfChar spl);
        abstract void copyIntoChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract boolean copyIntoWithCancelChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveSink.OfChar wrapSinkChar(PrimitiveSink.OfDouble sink);
        abstract PrimitiveSpliterator.OfDouble wrapSpliteratorChar(PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveNode.OfDouble evaluateChar(PrimitiveSpliterator.OfChar spl, boolean flatten, PrimitiveFunction.OfInt<double[]> gen);
        abstract long exactOutputSizeIfKnownShort(PrimitiveSpliterator.OfShort spliterator);
        abstract PrimitiveSink.OfDouble wrapAndCopyIntoShort(PrimitiveSink.OfShort sink, PrimitiveSpliterator.OfShort spl);
        abstract void copyIntoShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract boolean copyIntoWithCancelShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveSink.OfShort wrapSinkShort(PrimitiveSink.OfDouble sink);
        abstract PrimitiveSpliterator.OfDouble wrapSpliteratorShort(PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveNode.OfDouble evaluateShort(PrimitiveSpliterator.OfShort spl, boolean flatten, PrimitiveFunction.OfInt<double[]> gen);
        abstract long exactOutputSizeIfKnownByte(PrimitiveSpliterator.OfByte spliterator);
        abstract PrimitiveSink.OfDouble wrapAndCopyIntoByte(PrimitiveSink.OfByte sink, PrimitiveSpliterator.OfByte spl);
        abstract void copyIntoByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract boolean copyIntoWithCancelByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveSink.OfByte wrapSinkByte(PrimitiveSink.OfDouble sink);
        abstract PrimitiveSpliterator.OfDouble wrapSpliteratorByte(PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveNode.OfDouble evaluateByte(PrimitiveSpliterator.OfByte spl, boolean flatten, PrimitiveFunction.OfInt<double[]> gen);
        abstract long exactOutputSizeIfKnownBoolean(PrimitiveSpliterator.OfBoolean spliterator);
        abstract PrimitiveSink.OfDouble wrapAndCopyIntoBoolean(PrimitiveSink.OfBoolean sink, PrimitiveSpliterator.OfBoolean spl);
        abstract void copyIntoBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract boolean copyIntoWithCancelBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveSink.OfBoolean wrapSinkBoolean(PrimitiveSink.OfDouble sink);
        abstract PrimitiveSpliterator.OfDouble wrapSpliteratorBoolean(PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveNode.OfDouble evaluateBoolean(PrimitiveSpliterator.OfBoolean spl, boolean flatten, PrimitiveFunction.OfInt<double[]> gen);
        abstract PrimitiveNode.Builder.OfDouble makeNodeBuilder(long exactSizeIfKnown, PrimitiveFunction.OfInt<double[]> gen);
    }
    abstract static class OfLong {
        abstract int getStreamAndOpFlags();
        abstract long exactOutputSizeIfKnownDouble(PrimitiveSpliterator.OfDouble spliterator);
        abstract PrimitiveSink.OfLong wrapAndCopyIntoDouble(PrimitiveSink.OfDouble sink, PrimitiveSpliterator.OfDouble spl);
        abstract void copyIntoDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract boolean copyIntoWithCancelDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveSink.OfDouble wrapSinkDouble(PrimitiveSink.OfLong sink);
        abstract PrimitiveSpliterator.OfLong wrapSpliteratorDouble(PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveNode.OfLong evaluateDouble(PrimitiveSpliterator.OfDouble spl, boolean flatten, PrimitiveFunction.OfInt<long[]> gen);
        abstract long exactOutputSizeIfKnownLong(PrimitiveSpliterator.OfLong spliterator);
        abstract PrimitiveSink.OfLong wrapAndCopyIntoLong(PrimitiveSink.OfLong sink, PrimitiveSpliterator.OfLong spl);
        abstract void copyIntoLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract boolean copyIntoWithCancelLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveSink.OfLong wrapSinkLong(PrimitiveSink.OfLong sink);
        abstract PrimitiveSpliterator.OfLong wrapSpliteratorLong(PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveNode.OfLong evaluateLong(PrimitiveSpliterator.OfLong spl, boolean flatten, PrimitiveFunction.OfInt<long[]> gen);
        abstract long exactOutputSizeIfKnownInt(PrimitiveSpliterator.OfInt spliterator);
        abstract PrimitiveSink.OfLong wrapAndCopyIntoInt(PrimitiveSink.OfInt sink, PrimitiveSpliterator.OfInt spl);
        abstract void copyIntoInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract boolean copyIntoWithCancelInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveSink.OfInt wrapSinkInt(PrimitiveSink.OfLong sink);
        abstract PrimitiveSpliterator.OfLong wrapSpliteratorInt(PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveNode.OfLong evaluateInt(PrimitiveSpliterator.OfInt spl, boolean flatten, PrimitiveFunction.OfInt<long[]> gen);
        abstract long exactOutputSizeIfKnownFloat(PrimitiveSpliterator.OfFloat spliterator);
        abstract PrimitiveSink.OfLong wrapAndCopyIntoFloat(PrimitiveSink.OfFloat sink, PrimitiveSpliterator.OfFloat spl);
        abstract void copyIntoFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract boolean copyIntoWithCancelFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveSink.OfFloat wrapSinkFloat(PrimitiveSink.OfLong sink);
        abstract PrimitiveSpliterator.OfLong wrapSpliteratorFloat(PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveNode.OfLong evaluateFloat(PrimitiveSpliterator.OfFloat spl, boolean flatten, PrimitiveFunction.OfInt<long[]> gen);
        abstract long exactOutputSizeIfKnownChar(PrimitiveSpliterator.OfChar spliterator);
        abstract PrimitiveSink.OfLong wrapAndCopyIntoChar(PrimitiveSink.OfChar sink, PrimitiveSpliterator.OfChar spl);
        abstract void copyIntoChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract boolean copyIntoWithCancelChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveSink.OfChar wrapSinkChar(PrimitiveSink.OfLong sink);
        abstract PrimitiveSpliterator.OfLong wrapSpliteratorChar(PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveNode.OfLong evaluateChar(PrimitiveSpliterator.OfChar spl, boolean flatten, PrimitiveFunction.OfInt<long[]> gen);
        abstract long exactOutputSizeIfKnownShort(PrimitiveSpliterator.OfShort spliterator);
        abstract PrimitiveSink.OfLong wrapAndCopyIntoShort(PrimitiveSink.OfShort sink, PrimitiveSpliterator.OfShort spl);
        abstract void copyIntoShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract boolean copyIntoWithCancelShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveSink.OfShort wrapSinkShort(PrimitiveSink.OfLong sink);
        abstract PrimitiveSpliterator.OfLong wrapSpliteratorShort(PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveNode.OfLong evaluateShort(PrimitiveSpliterator.OfShort spl, boolean flatten, PrimitiveFunction.OfInt<long[]> gen);
        abstract long exactOutputSizeIfKnownByte(PrimitiveSpliterator.OfByte spliterator);
        abstract PrimitiveSink.OfLong wrapAndCopyIntoByte(PrimitiveSink.OfByte sink, PrimitiveSpliterator.OfByte spl);
        abstract void copyIntoByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract boolean copyIntoWithCancelByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveSink.OfByte wrapSinkByte(PrimitiveSink.OfLong sink);
        abstract PrimitiveSpliterator.OfLong wrapSpliteratorByte(PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveNode.OfLong evaluateByte(PrimitiveSpliterator.OfByte spl, boolean flatten, PrimitiveFunction.OfInt<long[]> gen);
        abstract long exactOutputSizeIfKnownBoolean(PrimitiveSpliterator.OfBoolean spliterator);
        abstract PrimitiveSink.OfLong wrapAndCopyIntoBoolean(PrimitiveSink.OfBoolean sink, PrimitiveSpliterator.OfBoolean spl);
        abstract void copyIntoBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract boolean copyIntoWithCancelBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveSink.OfBoolean wrapSinkBoolean(PrimitiveSink.OfLong sink);
        abstract PrimitiveSpliterator.OfLong wrapSpliteratorBoolean(PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveNode.OfLong evaluateBoolean(PrimitiveSpliterator.OfBoolean spl, boolean flatten, PrimitiveFunction.OfInt<long[]> gen);
        abstract PrimitiveNode.Builder.OfLong makeNodeBuilder(long exactSizeIfKnown, PrimitiveFunction.OfInt<long[]> gen);
    }
    abstract static class OfInt {
        abstract int getStreamAndOpFlags();
        abstract long exactOutputSizeIfKnownDouble(PrimitiveSpliterator.OfDouble spliterator);
        abstract PrimitiveSink.OfInt wrapAndCopyIntoDouble(PrimitiveSink.OfDouble sink, PrimitiveSpliterator.OfDouble spl);
        abstract void copyIntoDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract boolean copyIntoWithCancelDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveSink.OfDouble wrapSinkDouble(PrimitiveSink.OfInt sink);
        abstract PrimitiveSpliterator.OfInt wrapSpliteratorDouble(PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveNode.OfInt evaluateDouble(PrimitiveSpliterator.OfDouble spl, boolean flatten, PrimitiveFunction.OfInt<int[]> gen);
        abstract long exactOutputSizeIfKnownLong(PrimitiveSpliterator.OfLong spliterator);
        abstract PrimitiveSink.OfInt wrapAndCopyIntoLong(PrimitiveSink.OfLong sink, PrimitiveSpliterator.OfLong spl);
        abstract void copyIntoLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract boolean copyIntoWithCancelLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveSink.OfLong wrapSinkLong(PrimitiveSink.OfInt sink);
        abstract PrimitiveSpliterator.OfInt wrapSpliteratorLong(PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveNode.OfInt evaluateLong(PrimitiveSpliterator.OfLong spl, boolean flatten, PrimitiveFunction.OfInt<int[]> gen);
        abstract long exactOutputSizeIfKnownInt(PrimitiveSpliterator.OfInt spliterator);
        abstract PrimitiveSink.OfInt wrapAndCopyIntoInt(PrimitiveSink.OfInt sink, PrimitiveSpliterator.OfInt spl);
        abstract void copyIntoInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract boolean copyIntoWithCancelInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveSink.OfInt wrapSinkInt(PrimitiveSink.OfInt sink);
        abstract PrimitiveSpliterator.OfInt wrapSpliteratorInt(PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveNode.OfInt evaluateInt(PrimitiveSpliterator.OfInt spl, boolean flatten, PrimitiveFunction.OfInt<int[]> gen);
        abstract long exactOutputSizeIfKnownFloat(PrimitiveSpliterator.OfFloat spliterator);
        abstract PrimitiveSink.OfInt wrapAndCopyIntoFloat(PrimitiveSink.OfFloat sink, PrimitiveSpliterator.OfFloat spl);
        abstract void copyIntoFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract boolean copyIntoWithCancelFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveSink.OfFloat wrapSinkFloat(PrimitiveSink.OfInt sink);
        abstract PrimitiveSpliterator.OfInt wrapSpliteratorFloat(PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveNode.OfInt evaluateFloat(PrimitiveSpliterator.OfFloat spl, boolean flatten, PrimitiveFunction.OfInt<int[]> gen);
        abstract long exactOutputSizeIfKnownChar(PrimitiveSpliterator.OfChar spliterator);
        abstract PrimitiveSink.OfInt wrapAndCopyIntoChar(PrimitiveSink.OfChar sink, PrimitiveSpliterator.OfChar spl);
        abstract void copyIntoChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract boolean copyIntoWithCancelChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveSink.OfChar wrapSinkChar(PrimitiveSink.OfInt sink);
        abstract PrimitiveSpliterator.OfInt wrapSpliteratorChar(PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveNode.OfInt evaluateChar(PrimitiveSpliterator.OfChar spl, boolean flatten, PrimitiveFunction.OfInt<int[]> gen);
        abstract long exactOutputSizeIfKnownShort(PrimitiveSpliterator.OfShort spliterator);
        abstract PrimitiveSink.OfInt wrapAndCopyIntoShort(PrimitiveSink.OfShort sink, PrimitiveSpliterator.OfShort spl);
        abstract void copyIntoShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract boolean copyIntoWithCancelShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveSink.OfShort wrapSinkShort(PrimitiveSink.OfInt sink);
        abstract PrimitiveSpliterator.OfInt wrapSpliteratorShort(PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveNode.OfInt evaluateShort(PrimitiveSpliterator.OfShort spl, boolean flatten, PrimitiveFunction.OfInt<int[]> gen);
        abstract long exactOutputSizeIfKnownByte(PrimitiveSpliterator.OfByte spliterator);
        abstract PrimitiveSink.OfInt wrapAndCopyIntoByte(PrimitiveSink.OfByte sink, PrimitiveSpliterator.OfByte spl);
        abstract void copyIntoByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract boolean copyIntoWithCancelByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveSink.OfByte wrapSinkByte(PrimitiveSink.OfInt sink);
        abstract PrimitiveSpliterator.OfInt wrapSpliteratorByte(PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveNode.OfInt evaluateByte(PrimitiveSpliterator.OfByte spl, boolean flatten, PrimitiveFunction.OfInt<int[]> gen);
        abstract long exactOutputSizeIfKnownBoolean(PrimitiveSpliterator.OfBoolean spliterator);
        abstract PrimitiveSink.OfInt wrapAndCopyIntoBoolean(PrimitiveSink.OfBoolean sink, PrimitiveSpliterator.OfBoolean spl);
        abstract void copyIntoBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract boolean copyIntoWithCancelBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveSink.OfBoolean wrapSinkBoolean(PrimitiveSink.OfInt sink);
        abstract PrimitiveSpliterator.OfInt wrapSpliteratorBoolean(PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveNode.OfInt evaluateBoolean(PrimitiveSpliterator.OfBoolean spl, boolean flatten, PrimitiveFunction.OfInt<int[]> gen);
        abstract PrimitiveNode.Builder.OfInt makeNodeBuilder(long exactSizeIfKnown, PrimitiveFunction.OfInt<int[]> gen);
    }
    abstract static class OfFloat {
        abstract int getStreamAndOpFlags();
        abstract long exactOutputSizeIfKnownDouble(PrimitiveSpliterator.OfDouble spliterator);
        abstract PrimitiveSink.OfFloat wrapAndCopyIntoDouble(PrimitiveSink.OfDouble sink, PrimitiveSpliterator.OfDouble spl);
        abstract void copyIntoDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract boolean copyIntoWithCancelDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveSink.OfDouble wrapSinkDouble(PrimitiveSink.OfFloat sink);
        abstract PrimitiveSpliterator.OfFloat wrapSpliteratorDouble(PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveNode.OfFloat evaluateDouble(PrimitiveSpliterator.OfDouble spl, boolean flatten, PrimitiveFunction.OfInt<float[]> gen);
        abstract long exactOutputSizeIfKnownLong(PrimitiveSpliterator.OfLong spliterator);
        abstract PrimitiveSink.OfFloat wrapAndCopyIntoLong(PrimitiveSink.OfLong sink, PrimitiveSpliterator.OfLong spl);
        abstract void copyIntoLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract boolean copyIntoWithCancelLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveSink.OfLong wrapSinkLong(PrimitiveSink.OfFloat sink);
        abstract PrimitiveSpliterator.OfFloat wrapSpliteratorLong(PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveNode.OfFloat evaluateLong(PrimitiveSpliterator.OfLong spl, boolean flatten, PrimitiveFunction.OfInt<float[]> gen);
        abstract long exactOutputSizeIfKnownInt(PrimitiveSpliterator.OfInt spliterator);
        abstract PrimitiveSink.OfFloat wrapAndCopyIntoInt(PrimitiveSink.OfInt sink, PrimitiveSpliterator.OfInt spl);
        abstract void copyIntoInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract boolean copyIntoWithCancelInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveSink.OfInt wrapSinkInt(PrimitiveSink.OfFloat sink);
        abstract PrimitiveSpliterator.OfFloat wrapSpliteratorInt(PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveNode.OfFloat evaluateInt(PrimitiveSpliterator.OfInt spl, boolean flatten, PrimitiveFunction.OfInt<float[]> gen);
        abstract long exactOutputSizeIfKnownFloat(PrimitiveSpliterator.OfFloat spliterator);
        abstract PrimitiveSink.OfFloat wrapAndCopyIntoFloat(PrimitiveSink.OfFloat sink, PrimitiveSpliterator.OfFloat spl);
        abstract void copyIntoFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract boolean copyIntoWithCancelFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveSink.OfFloat wrapSinkFloat(PrimitiveSink.OfFloat sink);
        abstract PrimitiveSpliterator.OfFloat wrapSpliteratorFloat(PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveNode.OfFloat evaluateFloat(PrimitiveSpliterator.OfFloat spl, boolean flatten, PrimitiveFunction.OfInt<float[]> gen);
        abstract long exactOutputSizeIfKnownChar(PrimitiveSpliterator.OfChar spliterator);
        abstract PrimitiveSink.OfFloat wrapAndCopyIntoChar(PrimitiveSink.OfChar sink, PrimitiveSpliterator.OfChar spl);
        abstract void copyIntoChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract boolean copyIntoWithCancelChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveSink.OfChar wrapSinkChar(PrimitiveSink.OfFloat sink);
        abstract PrimitiveSpliterator.OfFloat wrapSpliteratorChar(PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveNode.OfFloat evaluateChar(PrimitiveSpliterator.OfChar spl, boolean flatten, PrimitiveFunction.OfInt<float[]> gen);
        abstract long exactOutputSizeIfKnownShort(PrimitiveSpliterator.OfShort spliterator);
        abstract PrimitiveSink.OfFloat wrapAndCopyIntoShort(PrimitiveSink.OfShort sink, PrimitiveSpliterator.OfShort spl);
        abstract void copyIntoShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract boolean copyIntoWithCancelShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveSink.OfShort wrapSinkShort(PrimitiveSink.OfFloat sink);
        abstract PrimitiveSpliterator.OfFloat wrapSpliteratorShort(PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveNode.OfFloat evaluateShort(PrimitiveSpliterator.OfShort spl, boolean flatten, PrimitiveFunction.OfInt<float[]> gen);
        abstract long exactOutputSizeIfKnownByte(PrimitiveSpliterator.OfByte spliterator);
        abstract PrimitiveSink.OfFloat wrapAndCopyIntoByte(PrimitiveSink.OfByte sink, PrimitiveSpliterator.OfByte spl);
        abstract void copyIntoByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract boolean copyIntoWithCancelByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveSink.OfByte wrapSinkByte(PrimitiveSink.OfFloat sink);
        abstract PrimitiveSpliterator.OfFloat wrapSpliteratorByte(PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveNode.OfFloat evaluateByte(PrimitiveSpliterator.OfByte spl, boolean flatten, PrimitiveFunction.OfInt<float[]> gen);
        abstract long exactOutputSizeIfKnownBoolean(PrimitiveSpliterator.OfBoolean spliterator);
        abstract PrimitiveSink.OfFloat wrapAndCopyIntoBoolean(PrimitiveSink.OfBoolean sink, PrimitiveSpliterator.OfBoolean spl);
        abstract void copyIntoBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract boolean copyIntoWithCancelBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveSink.OfBoolean wrapSinkBoolean(PrimitiveSink.OfFloat sink);
        abstract PrimitiveSpliterator.OfFloat wrapSpliteratorBoolean(PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveNode.OfFloat evaluateBoolean(PrimitiveSpliterator.OfBoolean spl, boolean flatten, PrimitiveFunction.OfInt<float[]> gen);
        abstract PrimitiveNode.Builder.OfFloat makeNodeBuilder(long exactSizeIfKnown, PrimitiveFunction.OfInt<float[]> gen);
    }
    abstract static class OfChar {
        abstract int getStreamAndOpFlags();
        abstract long exactOutputSizeIfKnownDouble(PrimitiveSpliterator.OfDouble spliterator);
        abstract PrimitiveSink.OfChar wrapAndCopyIntoDouble(PrimitiveSink.OfDouble sink, PrimitiveSpliterator.OfDouble spl);
        abstract void copyIntoDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract boolean copyIntoWithCancelDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveSink.OfDouble wrapSinkDouble(PrimitiveSink.OfChar sink);
        abstract PrimitiveSpliterator.OfChar wrapSpliteratorDouble(PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveNode.OfChar evaluateDouble(PrimitiveSpliterator.OfDouble spl, boolean flatten, PrimitiveFunction.OfInt<char[]> gen);
        abstract long exactOutputSizeIfKnownLong(PrimitiveSpliterator.OfLong spliterator);
        abstract PrimitiveSink.OfChar wrapAndCopyIntoLong(PrimitiveSink.OfLong sink, PrimitiveSpliterator.OfLong spl);
        abstract void copyIntoLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract boolean copyIntoWithCancelLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveSink.OfLong wrapSinkLong(PrimitiveSink.OfChar sink);
        abstract PrimitiveSpliterator.OfChar wrapSpliteratorLong(PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveNode.OfChar evaluateLong(PrimitiveSpliterator.OfLong spl, boolean flatten, PrimitiveFunction.OfInt<char[]> gen);
        abstract long exactOutputSizeIfKnownInt(PrimitiveSpliterator.OfInt spliterator);
        abstract PrimitiveSink.OfChar wrapAndCopyIntoInt(PrimitiveSink.OfInt sink, PrimitiveSpliterator.OfInt spl);
        abstract void copyIntoInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract boolean copyIntoWithCancelInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveSink.OfInt wrapSinkInt(PrimitiveSink.OfChar sink);
        abstract PrimitiveSpliterator.OfChar wrapSpliteratorInt(PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveNode.OfChar evaluateInt(PrimitiveSpliterator.OfInt spl, boolean flatten, PrimitiveFunction.OfInt<char[]> gen);
        abstract long exactOutputSizeIfKnownFloat(PrimitiveSpliterator.OfFloat spliterator);
        abstract PrimitiveSink.OfChar wrapAndCopyIntoFloat(PrimitiveSink.OfFloat sink, PrimitiveSpliterator.OfFloat spl);
        abstract void copyIntoFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract boolean copyIntoWithCancelFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveSink.OfFloat wrapSinkFloat(PrimitiveSink.OfChar sink);
        abstract PrimitiveSpliterator.OfChar wrapSpliteratorFloat(PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveNode.OfChar evaluateFloat(PrimitiveSpliterator.OfFloat spl, boolean flatten, PrimitiveFunction.OfInt<char[]> gen);
        abstract long exactOutputSizeIfKnownChar(PrimitiveSpliterator.OfChar spliterator);
        abstract PrimitiveSink.OfChar wrapAndCopyIntoChar(PrimitiveSink.OfChar sink, PrimitiveSpliterator.OfChar spl);
        abstract void copyIntoChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract boolean copyIntoWithCancelChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveSink.OfChar wrapSinkChar(PrimitiveSink.OfChar sink);
        abstract PrimitiveSpliterator.OfChar wrapSpliteratorChar(PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveNode.OfChar evaluateChar(PrimitiveSpliterator.OfChar spl, boolean flatten, PrimitiveFunction.OfInt<char[]> gen);
        abstract long exactOutputSizeIfKnownShort(PrimitiveSpliterator.OfShort spliterator);
        abstract PrimitiveSink.OfChar wrapAndCopyIntoShort(PrimitiveSink.OfShort sink, PrimitiveSpliterator.OfShort spl);
        abstract void copyIntoShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract boolean copyIntoWithCancelShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveSink.OfShort wrapSinkShort(PrimitiveSink.OfChar sink);
        abstract PrimitiveSpliterator.OfChar wrapSpliteratorShort(PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveNode.OfChar evaluateShort(PrimitiveSpliterator.OfShort spl, boolean flatten, PrimitiveFunction.OfInt<char[]> gen);
        abstract long exactOutputSizeIfKnownByte(PrimitiveSpliterator.OfByte spliterator);
        abstract PrimitiveSink.OfChar wrapAndCopyIntoByte(PrimitiveSink.OfByte sink, PrimitiveSpliterator.OfByte spl);
        abstract void copyIntoByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract boolean copyIntoWithCancelByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveSink.OfByte wrapSinkByte(PrimitiveSink.OfChar sink);
        abstract PrimitiveSpliterator.OfChar wrapSpliteratorByte(PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveNode.OfChar evaluateByte(PrimitiveSpliterator.OfByte spl, boolean flatten, PrimitiveFunction.OfInt<char[]> gen);
        abstract long exactOutputSizeIfKnownBoolean(PrimitiveSpliterator.OfBoolean spliterator);
        abstract PrimitiveSink.OfChar wrapAndCopyIntoBoolean(PrimitiveSink.OfBoolean sink, PrimitiveSpliterator.OfBoolean spl);
        abstract void copyIntoBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract boolean copyIntoWithCancelBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveSink.OfBoolean wrapSinkBoolean(PrimitiveSink.OfChar sink);
        abstract PrimitiveSpliterator.OfChar wrapSpliteratorBoolean(PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveNode.OfChar evaluateBoolean(PrimitiveSpliterator.OfBoolean spl, boolean flatten, PrimitiveFunction.OfInt<char[]> gen);
        abstract PrimitiveNode.Builder.OfChar makeNodeBuilder(long exactSizeIfKnown, PrimitiveFunction.OfInt<char[]> gen);
    }
    abstract static class OfShort {
        abstract int getStreamAndOpFlags();
        abstract long exactOutputSizeIfKnownDouble(PrimitiveSpliterator.OfDouble spliterator);
        abstract PrimitiveSink.OfShort wrapAndCopyIntoDouble(PrimitiveSink.OfDouble sink, PrimitiveSpliterator.OfDouble spl);
        abstract void copyIntoDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract boolean copyIntoWithCancelDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveSink.OfDouble wrapSinkDouble(PrimitiveSink.OfShort sink);
        abstract PrimitiveSpliterator.OfShort wrapSpliteratorDouble(PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveNode.OfShort evaluateDouble(PrimitiveSpliterator.OfDouble spl, boolean flatten, PrimitiveFunction.OfInt<short[]> gen);
        abstract long exactOutputSizeIfKnownLong(PrimitiveSpliterator.OfLong spliterator);
        abstract PrimitiveSink.OfShort wrapAndCopyIntoLong(PrimitiveSink.OfLong sink, PrimitiveSpliterator.OfLong spl);
        abstract void copyIntoLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract boolean copyIntoWithCancelLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveSink.OfLong wrapSinkLong(PrimitiveSink.OfShort sink);
        abstract PrimitiveSpliterator.OfShort wrapSpliteratorLong(PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveNode.OfShort evaluateLong(PrimitiveSpliterator.OfLong spl, boolean flatten, PrimitiveFunction.OfInt<short[]> gen);
        abstract long exactOutputSizeIfKnownInt(PrimitiveSpliterator.OfInt spliterator);
        abstract PrimitiveSink.OfShort wrapAndCopyIntoInt(PrimitiveSink.OfInt sink, PrimitiveSpliterator.OfInt spl);
        abstract void copyIntoInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract boolean copyIntoWithCancelInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveSink.OfInt wrapSinkInt(PrimitiveSink.OfShort sink);
        abstract PrimitiveSpliterator.OfShort wrapSpliteratorInt(PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveNode.OfShort evaluateInt(PrimitiveSpliterator.OfInt spl, boolean flatten, PrimitiveFunction.OfInt<short[]> gen);
        abstract long exactOutputSizeIfKnownFloat(PrimitiveSpliterator.OfFloat spliterator);
        abstract PrimitiveSink.OfShort wrapAndCopyIntoFloat(PrimitiveSink.OfFloat sink, PrimitiveSpliterator.OfFloat spl);
        abstract void copyIntoFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract boolean copyIntoWithCancelFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveSink.OfFloat wrapSinkFloat(PrimitiveSink.OfShort sink);
        abstract PrimitiveSpliterator.OfShort wrapSpliteratorFloat(PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveNode.OfShort evaluateFloat(PrimitiveSpliterator.OfFloat spl, boolean flatten, PrimitiveFunction.OfInt<short[]> gen);
        abstract long exactOutputSizeIfKnownChar(PrimitiveSpliterator.OfChar spliterator);
        abstract PrimitiveSink.OfShort wrapAndCopyIntoChar(PrimitiveSink.OfChar sink, PrimitiveSpliterator.OfChar spl);
        abstract void copyIntoChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract boolean copyIntoWithCancelChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveSink.OfChar wrapSinkChar(PrimitiveSink.OfShort sink);
        abstract PrimitiveSpliterator.OfShort wrapSpliteratorChar(PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveNode.OfShort evaluateChar(PrimitiveSpliterator.OfChar spl, boolean flatten, PrimitiveFunction.OfInt<short[]> gen);
        abstract long exactOutputSizeIfKnownShort(PrimitiveSpliterator.OfShort spliterator);
        abstract PrimitiveSink.OfShort wrapAndCopyIntoShort(PrimitiveSink.OfShort sink, PrimitiveSpliterator.OfShort spl);
        abstract void copyIntoShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract boolean copyIntoWithCancelShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveSink.OfShort wrapSinkShort(PrimitiveSink.OfShort sink);
        abstract PrimitiveSpliterator.OfShort wrapSpliteratorShort(PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveNode.OfShort evaluateShort(PrimitiveSpliterator.OfShort spl, boolean flatten, PrimitiveFunction.OfInt<short[]> gen);
        abstract long exactOutputSizeIfKnownByte(PrimitiveSpliterator.OfByte spliterator);
        abstract PrimitiveSink.OfShort wrapAndCopyIntoByte(PrimitiveSink.OfByte sink, PrimitiveSpliterator.OfByte spl);
        abstract void copyIntoByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract boolean copyIntoWithCancelByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveSink.OfByte wrapSinkByte(PrimitiveSink.OfShort sink);
        abstract PrimitiveSpliterator.OfShort wrapSpliteratorByte(PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveNode.OfShort evaluateByte(PrimitiveSpliterator.OfByte spl, boolean flatten, PrimitiveFunction.OfInt<short[]> gen);
        abstract long exactOutputSizeIfKnownBoolean(PrimitiveSpliterator.OfBoolean spliterator);
        abstract PrimitiveSink.OfShort wrapAndCopyIntoBoolean(PrimitiveSink.OfBoolean sink, PrimitiveSpliterator.OfBoolean spl);
        abstract void copyIntoBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract boolean copyIntoWithCancelBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveSink.OfBoolean wrapSinkBoolean(PrimitiveSink.OfShort sink);
        abstract PrimitiveSpliterator.OfShort wrapSpliteratorBoolean(PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveNode.OfShort evaluateBoolean(PrimitiveSpliterator.OfBoolean spl, boolean flatten, PrimitiveFunction.OfInt<short[]> gen);
        abstract PrimitiveNode.Builder.OfShort makeNodeBuilder(long exactSizeIfKnown, PrimitiveFunction.OfInt<short[]> gen);
    }
    abstract static class OfByte {
        abstract int getStreamAndOpFlags();
        abstract long exactOutputSizeIfKnownDouble(PrimitiveSpliterator.OfDouble spliterator);
        abstract PrimitiveSink.OfByte wrapAndCopyIntoDouble(PrimitiveSink.OfDouble sink, PrimitiveSpliterator.OfDouble spl);
        abstract void copyIntoDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract boolean copyIntoWithCancelDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveSink.OfDouble wrapSinkDouble(PrimitiveSink.OfByte sink);
        abstract PrimitiveSpliterator.OfByte wrapSpliteratorDouble(PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveNode.OfByte evaluateDouble(PrimitiveSpliterator.OfDouble spl, boolean flatten, PrimitiveFunction.OfInt<byte[]> gen);
        abstract long exactOutputSizeIfKnownLong(PrimitiveSpliterator.OfLong spliterator);
        abstract PrimitiveSink.OfByte wrapAndCopyIntoLong(PrimitiveSink.OfLong sink, PrimitiveSpliterator.OfLong spl);
        abstract void copyIntoLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract boolean copyIntoWithCancelLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveSink.OfLong wrapSinkLong(PrimitiveSink.OfByte sink);
        abstract PrimitiveSpliterator.OfByte wrapSpliteratorLong(PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveNode.OfByte evaluateLong(PrimitiveSpliterator.OfLong spl, boolean flatten, PrimitiveFunction.OfInt<byte[]> gen);
        abstract long exactOutputSizeIfKnownInt(PrimitiveSpliterator.OfInt spliterator);
        abstract PrimitiveSink.OfByte wrapAndCopyIntoInt(PrimitiveSink.OfInt sink, PrimitiveSpliterator.OfInt spl);
        abstract void copyIntoInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract boolean copyIntoWithCancelInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveSink.OfInt wrapSinkInt(PrimitiveSink.OfByte sink);
        abstract PrimitiveSpliterator.OfByte wrapSpliteratorInt(PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveNode.OfByte evaluateInt(PrimitiveSpliterator.OfInt spl, boolean flatten, PrimitiveFunction.OfInt<byte[]> gen);
        abstract long exactOutputSizeIfKnownFloat(PrimitiveSpliterator.OfFloat spliterator);
        abstract PrimitiveSink.OfByte wrapAndCopyIntoFloat(PrimitiveSink.OfFloat sink, PrimitiveSpliterator.OfFloat spl);
        abstract void copyIntoFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract boolean copyIntoWithCancelFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveSink.OfFloat wrapSinkFloat(PrimitiveSink.OfByte sink);
        abstract PrimitiveSpliterator.OfByte wrapSpliteratorFloat(PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveNode.OfByte evaluateFloat(PrimitiveSpliterator.OfFloat spl, boolean flatten, PrimitiveFunction.OfInt<byte[]> gen);
        abstract long exactOutputSizeIfKnownChar(PrimitiveSpliterator.OfChar spliterator);
        abstract PrimitiveSink.OfByte wrapAndCopyIntoChar(PrimitiveSink.OfChar sink, PrimitiveSpliterator.OfChar spl);
        abstract void copyIntoChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract boolean copyIntoWithCancelChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveSink.OfChar wrapSinkChar(PrimitiveSink.OfByte sink);
        abstract PrimitiveSpliterator.OfByte wrapSpliteratorChar(PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveNode.OfByte evaluateChar(PrimitiveSpliterator.OfChar spl, boolean flatten, PrimitiveFunction.OfInt<byte[]> gen);
        abstract long exactOutputSizeIfKnownShort(PrimitiveSpliterator.OfShort spliterator);
        abstract PrimitiveSink.OfByte wrapAndCopyIntoShort(PrimitiveSink.OfShort sink, PrimitiveSpliterator.OfShort spl);
        abstract void copyIntoShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract boolean copyIntoWithCancelShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveSink.OfShort wrapSinkShort(PrimitiveSink.OfByte sink);
        abstract PrimitiveSpliterator.OfByte wrapSpliteratorShort(PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveNode.OfByte evaluateShort(PrimitiveSpliterator.OfShort spl, boolean flatten, PrimitiveFunction.OfInt<byte[]> gen);
        abstract long exactOutputSizeIfKnownByte(PrimitiveSpliterator.OfByte spliterator);
        abstract PrimitiveSink.OfByte wrapAndCopyIntoByte(PrimitiveSink.OfByte sink, PrimitiveSpliterator.OfByte spl);
        abstract void copyIntoByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract boolean copyIntoWithCancelByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveSink.OfByte wrapSinkByte(PrimitiveSink.OfByte sink);
        abstract PrimitiveSpliterator.OfByte wrapSpliteratorByte(PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveNode.OfByte evaluateByte(PrimitiveSpliterator.OfByte spl, boolean flatten, PrimitiveFunction.OfInt<byte[]> gen);
        abstract long exactOutputSizeIfKnownBoolean(PrimitiveSpliterator.OfBoolean spliterator);
        abstract PrimitiveSink.OfByte wrapAndCopyIntoBoolean(PrimitiveSink.OfBoolean sink, PrimitiveSpliterator.OfBoolean spl);
        abstract void copyIntoBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract boolean copyIntoWithCancelBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveSink.OfBoolean wrapSinkBoolean(PrimitiveSink.OfByte sink);
        abstract PrimitiveSpliterator.OfByte wrapSpliteratorBoolean(PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveNode.OfByte evaluateBoolean(PrimitiveSpliterator.OfBoolean spl, boolean flatten, PrimitiveFunction.OfInt<byte[]> gen);
        abstract PrimitiveNode.Builder.OfByte makeNodeBuilder(long exactSizeIfKnown, PrimitiveFunction.OfInt<byte[]> gen);
    }
    abstract static class OfBoolean {
        abstract int getStreamAndOpFlags();
        abstract long exactOutputSizeIfKnownDouble(PrimitiveSpliterator.OfDouble spliterator);
        abstract PrimitiveSink.OfBoolean wrapAndCopyIntoDouble(PrimitiveSink.OfDouble sink, PrimitiveSpliterator.OfDouble spl);
        abstract void copyIntoDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract boolean copyIntoWithCancelDouble(PrimitiveSink.OfDouble wrappedSink, PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveSink.OfDouble wrapSinkDouble(PrimitiveSink.OfBoolean sink);
        abstract PrimitiveSpliterator.OfBoolean wrapSpliteratorDouble(PrimitiveSpliterator.OfDouble spl);
        abstract PrimitiveNode.OfBoolean evaluateDouble(PrimitiveSpliterator.OfDouble spl, boolean flatten, PrimitiveFunction.OfInt<boolean[]> gen);
        abstract long exactOutputSizeIfKnownLong(PrimitiveSpliterator.OfLong spliterator);
        abstract PrimitiveSink.OfBoolean wrapAndCopyIntoLong(PrimitiveSink.OfLong sink, PrimitiveSpliterator.OfLong spl);
        abstract void copyIntoLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract boolean copyIntoWithCancelLong(PrimitiveSink.OfLong wrappedSink, PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveSink.OfLong wrapSinkLong(PrimitiveSink.OfBoolean sink);
        abstract PrimitiveSpliterator.OfBoolean wrapSpliteratorLong(PrimitiveSpliterator.OfLong spl);
        abstract PrimitiveNode.OfBoolean evaluateLong(PrimitiveSpliterator.OfLong spl, boolean flatten, PrimitiveFunction.OfInt<boolean[]> gen);
        abstract long exactOutputSizeIfKnownInt(PrimitiveSpliterator.OfInt spliterator);
        abstract PrimitiveSink.OfBoolean wrapAndCopyIntoInt(PrimitiveSink.OfInt sink, PrimitiveSpliterator.OfInt spl);
        abstract void copyIntoInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract boolean copyIntoWithCancelInt(PrimitiveSink.OfInt wrappedSink, PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveSink.OfInt wrapSinkInt(PrimitiveSink.OfBoolean sink);
        abstract PrimitiveSpliterator.OfBoolean wrapSpliteratorInt(PrimitiveSpliterator.OfInt spl);
        abstract PrimitiveNode.OfBoolean evaluateInt(PrimitiveSpliterator.OfInt spl, boolean flatten, PrimitiveFunction.OfInt<boolean[]> gen);
        abstract long exactOutputSizeIfKnownFloat(PrimitiveSpliterator.OfFloat spliterator);
        abstract PrimitiveSink.OfBoolean wrapAndCopyIntoFloat(PrimitiveSink.OfFloat sink, PrimitiveSpliterator.OfFloat spl);
        abstract void copyIntoFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract boolean copyIntoWithCancelFloat(PrimitiveSink.OfFloat wrappedSink, PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveSink.OfFloat wrapSinkFloat(PrimitiveSink.OfBoolean sink);
        abstract PrimitiveSpliterator.OfBoolean wrapSpliteratorFloat(PrimitiveSpliterator.OfFloat spl);
        abstract PrimitiveNode.OfBoolean evaluateFloat(PrimitiveSpliterator.OfFloat spl, boolean flatten, PrimitiveFunction.OfInt<boolean[]> gen);
        abstract long exactOutputSizeIfKnownChar(PrimitiveSpliterator.OfChar spliterator);
        abstract PrimitiveSink.OfBoolean wrapAndCopyIntoChar(PrimitiveSink.OfChar sink, PrimitiveSpliterator.OfChar spl);
        abstract void copyIntoChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract boolean copyIntoWithCancelChar(PrimitiveSink.OfChar wrappedSink, PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveSink.OfChar wrapSinkChar(PrimitiveSink.OfBoolean sink);
        abstract PrimitiveSpliterator.OfBoolean wrapSpliteratorChar(PrimitiveSpliterator.OfChar spl);
        abstract PrimitiveNode.OfBoolean evaluateChar(PrimitiveSpliterator.OfChar spl, boolean flatten, PrimitiveFunction.OfInt<boolean[]> gen);
        abstract long exactOutputSizeIfKnownShort(PrimitiveSpliterator.OfShort spliterator);
        abstract PrimitiveSink.OfBoolean wrapAndCopyIntoShort(PrimitiveSink.OfShort sink, PrimitiveSpliterator.OfShort spl);
        abstract void copyIntoShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract boolean copyIntoWithCancelShort(PrimitiveSink.OfShort wrappedSink, PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveSink.OfShort wrapSinkShort(PrimitiveSink.OfBoolean sink);
        abstract PrimitiveSpliterator.OfBoolean wrapSpliteratorShort(PrimitiveSpliterator.OfShort spl);
        abstract PrimitiveNode.OfBoolean evaluateShort(PrimitiveSpliterator.OfShort spl, boolean flatten, PrimitiveFunction.OfInt<boolean[]> gen);
        abstract long exactOutputSizeIfKnownByte(PrimitiveSpliterator.OfByte spliterator);
        abstract PrimitiveSink.OfBoolean wrapAndCopyIntoByte(PrimitiveSink.OfByte sink, PrimitiveSpliterator.OfByte spl);
        abstract void copyIntoByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract boolean copyIntoWithCancelByte(PrimitiveSink.OfByte wrappedSink, PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveSink.OfByte wrapSinkByte(PrimitiveSink.OfBoolean sink);
        abstract PrimitiveSpliterator.OfBoolean wrapSpliteratorByte(PrimitiveSpliterator.OfByte spl);
        abstract PrimitiveNode.OfBoolean evaluateByte(PrimitiveSpliterator.OfByte spl, boolean flatten, PrimitiveFunction.OfInt<boolean[]> gen);
        abstract long exactOutputSizeIfKnownBoolean(PrimitiveSpliterator.OfBoolean spliterator);
        abstract PrimitiveSink.OfBoolean wrapAndCopyIntoBoolean(PrimitiveSink.OfBoolean sink, PrimitiveSpliterator.OfBoolean spl);
        abstract void copyIntoBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract boolean copyIntoWithCancelBoolean(PrimitiveSink.OfBoolean wrappedSink, PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveSink.OfBoolean wrapSinkBoolean(PrimitiveSink.OfBoolean sink);
        abstract PrimitiveSpliterator.OfBoolean wrapSpliteratorBoolean(PrimitiveSpliterator.OfBoolean spl);
        abstract PrimitiveNode.OfBoolean evaluateBoolean(PrimitiveSpliterator.OfBoolean spl, boolean flatten, PrimitiveFunction.OfInt<boolean[]> gen);
        abstract PrimitiveNode.Builder.OfBoolean makeNodeBuilder(long exactSizeIfKnown, PrimitiveFunction.OfInt<boolean[]> gen);
    }
}
